__author__ = 'Den'

TILE_WIDTH = 64
TILE_HEIGHT = 64

MAP_WIDTH_IN_TILES = 250
MAP_HEIGHT_IN_TILES = 500

WORLD_WIDTH = TILE_WIDTH * MAP_WIDTH_IN_TILES
WORLD_HEIGHT = TILE_HEIGHT/2 * MAP_HEIGHT_IN_TILES
