__author__ = 'Den'

import os.path

TILE_WIDTH = 64
TILE_HEIGHT = 64

MAP_WIDTH_IN_TILES = 50
MAP_HEIGHT_IN_TILES = 12

WORLD_WIDTH = TILE_WIDTH * MAP_WIDTH_IN_TILES
WORLD_HEIGHT = TILE_HEIGHT/2 * MAP_HEIGHT_IN_TILES
DATA_DIR = os.path.realpath('data')